Repository wafflestudio/wacruit-web, pull requests merged in 2023-08, with the labels that each got.

#18 Feat/sso
  .gitignore
  index.html
  package.json
  public/icon/header/Alarm.svg
  public/icon/header/Apply.svg
  public/icon/header/Login.svg
  public/icon/header/Logout.svg
  public/icon/register/Register.svg
  src/apis/announcement.ts
  src/apis/auth.ts
  src/apis/environment.ts
  src/apis/problem.ts
  src/apis/recruiting.ts
  src/apis/user.ts
  src/apis/utility.ts
  src/components/home/Apply.tsx
  src/components/home/Header/Header.tsx
  src/components/rookie/Header/Header.tsx
  src/components/rookie/Progress/ProgressList.tsx
  src/components/solve/ProblemDescription/ProblemDescription.tsx
  src/main.tsx
  src/mocks/db/recruiting.ts
  src/mocks/handler/recruitingHandler.ts
  src/pages/Announcement.tsx
  src/pages/Dashboard.tsx
  src/pages/Home.tsx
  src/pages/Recruit.tsx
  src/pages/Resume.tsx
  src/pages/Rookie.tsx
  src/pages/Solve.tsx
  src/pages/Sso.tsx
  src/types/apiTypes.ts
  yarn.lock
Labels: documentation, enhancement, good first issue

#20 Hotfix: svg & styled components error
  src/components/Modal/Modal.tsx
  src/components/home/Apply.tsx
  src/components/home/icons/LockIcon.tsx
  src/components/home/icons/WaffleIcon.tsx
Labels: hotfix

#19 Hotfix: release cicd 브랜치명 수정 및 활성화
  .github/workflows/release.yml
  temp/README.md
  temp/release.yml
Labels: hotfix

#21 Feat: countdown
  index.html
  package.json
  public/image/home/countdown/CardBottomHalf.svg
  public/image/home/countdown/CardTopHalf.svg
  src/components/home/Banner.tsx
  src/components/home/Countdown.css
  src/components/home/Countdown.tsx
  yarn.lock
Labels: enhancement

#23 Hotfix/markdown
  src/GlobalStyles.tsx
  src/components/solve/ProblemDescription/ProblemDescription.tsx
  src/lib/MarkdownRenderer.tsx
  src/pages/Announcement.tsx
  src/pages/Dashboard.tsx
  src/pages/Rookie.tsx
Labels: enhancement

#22 Fix/auth & dashboard
  package.json
  public/icon/rookie/Portfolio.svg
  public/image/home/banner/WaffleEmpty.svg
  public/image/home/banner/WaffleFilled.svg
  public/image/home/service/Siksha.png
  public/image/home/service/Snuboard.png
  public/image/home/service/Snutt.png
  src/apis/auth.ts
  src/components/home/Apply.tsx
  src/components/home/Banner.tsx
  src/components/home/CalenderInner.tsx
  src/components/home/Header/Header.tsx
  src/components/home/Introduce.tsx
  src/components/home/Service.tsx
  src/components/rookie/Progress/PortfolioCard.tsx
  src/components/rookie/Progress/ProgressCard.tsx
  src/components/rookie/Progress/ProgressList.tsx
  src/components/rookie/Progress/progressCardAsset.ts
  src/lib/loading.ts
  src/main.tsx
  src/mocks/db/recruiting.ts
  src/pages/Announcement.tsx
  src/pages/Dashboard.tsx
  src/pages/Home.tsx
  src/pages/Loader/DashboardLoader.ts
  src/pages/Recruit.tsx
  src/pages/Resume.tsx
  src/pages/Rookie.tsx
  src/pages/Solve.tsx
  src/pages/Sso.tsx
  src/types/apiTypes.ts
  src/types/commonTypes.ts
  yarn.lock
Labels: enhancement

#41 Hotfix/markdown math
  package.json
  src/lib/MarkdownRenderer.tsx
  yarn.lock
Labels: enhancement

#43 FIX : 대시보드 '아래 내용'=>'위 내용'
  src/pages/Dashboard.tsx
Labels: bug

#45 Feat/new announcement modal
  src/components/home/Header/Header.tsx
  src/components/home/NotificationModal.tsx
  src/pages/Announcement.tsx
  src/pages/Home.tsx
Labels: enhancement

#46 Hotfix/testcase
  src/components/solve/ProblemDescription/TestCaseModal.tsx
  src/components/solve/ProblemDescription/common.tsx
Labels: bug

#65 FIX : 공지모달 max-height 설정 및 스크롤바 디자인
  src/components/home/NotificationModal.tsx
Labels: bug

#66 FIX : progressCard & resumeCard 화살표 중앙정렬 조정
  src/components/rookie/Progress/ProgressCard.tsx
  src/components/rookie/Progress/ResumeCard.tsx
Labels: bug

#86 Add: 서비스 캐러셀 애니메이션
  src/components/home/Service.tsx
Labels: enhancement

#91 Feat/multiple announcement modal
  src/apis/announcement.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/useModal.tsx
  src/components/Modal/useModals.tsx
  src/components/home/NotificationModal.tsx
  src/components/solve/ProblemDescription/ProblemDescription.tsx
  src/pages/Home.tsx
Labels: enhancement

#93 Fix: delete banner countdown line
  src/components/home/Countdown.css
Labels: enhancement

#98 hotfix: invalidate cahce when clear user
  src/pages/Dashboard.tsx
Labels: hotfix

#102 feat: recruit result view
  public/image/result/fail.svg
  public/image/result/pass.svg
  src/apis/recruiting.ts
  src/main.tsx
  src/pages/Dashboard.tsx
  src/pages/Loader/ResultLoader.ts
  src/pages/Result.tsx
Labels: enhancement

#92 Fix/announcement markdown
  src/components/home/NotificationModal.tsx
  src/pages/Announcement.tsx
Labels: enhancement

#105 Fix/result description
  src/pages/Result.tsx
Labels: enhancement
