Repository wafflestudio/wacruit-web, pull requests merged in 2023-07, with the labels that each got.

#5 Feat/solve page problem console
  index.html
  public/icon/AddTestCase.svg
  public/icon/CloseModal.svg
  src/components/solve/ProblemDescription.tsx
  src/components/solve/ProblemDescription/Modal.tsx
  src/components/solve/ProblemDescription/ProblemDescription.tsx
  src/components/solve/ProblemDescription/TestCaseModal.tsx
  src/components/solve/ProblemDescription/TestCaseTable.tsx
  src/components/solve/ProblemDescription/spacer.ts
  src/components/solve/ProblemDescription/styledComponents.tsx
  src/components/solve/ProblemDescription/useModal.tsx
  src/pages/Solve.tsx
Labels: enhancement

#6 Feat/rookie-and-mockAPIs
  .gitignore
  .yarnrc.yml
  public/icon/rookie/AnnounceRightArrow.svg
  public/icon/rookie/AnnounceRightArrowWhite.svg
  public/icon/rookie/CardRightArrow.svg
  public/icon/rookie/Check.svg
  public/icon/rookie/Code.svg
  public/icon/rookie/Pencil.svg
  public/icon/rookie/X.svg
  public/icon/rookie/logo.png
  src/components/rookie/Header/Header.tsx
  src/components/rookie/Progress/ProgressCard.tsx
  src/components/rookie/Progress/ProgressList.tsx
  src/components/rookie/Progress/progressCardAsset.ts
  src/components/rookie/QuestionaireInput/QuestionaireInput.tsx
  src/components/solve/ProblemDescription/styledComponents.tsx
  src/main.tsx
  src/mocks/db/user.ts
  src/mocks/handler/userHandler.ts
  src/mocks/handlers.ts
  src/mocks/types/types.ts
  src/pages/Resume.tsx
  src/pages/Rookie.tsx
Labels: enhancement

#9 Hotfix/solve import
  src/components/solve/ProblemDescription/common.tsx
  src/pages/Solve.tsx
Labels: bug, enhancement

#8 Feat/global styles
  src/GlobalStyles.tsx
Labels: enhancement, help wanted

#10 Feat/main
  font.d.ts
  index.html
  public/image/home/Stroke.svg
  public/image/home/banner/Eyes.svg
  public/image/home/banner/MousePointer.svg
  public/image/home/banner/ReadingGlass.svg
  public/image/home/members/Designer.svg
  public/image/home/members/Programmer.svg
  public/image/home/members/Rookie.svg
  public/image/home/process/Paper.svg
  public/image/home/process/People.svg
  public/image/home/process/Siren.svg
  public/image/home/share/Instagram.svg
  public/image/home/share/KakaoTalk.svg
  public/image/home/share/Share.svg
  public/image/home/stars/Star20.svg
  public/image/home/stars/Star30.svg
  public/image/home/stars/Star40.svg
  src/GlobalStyles.tsx
  src/components/home/Activity.tsx
  src/components/home/Apply.tsx
  src/components/home/Banner.tsx
  src/components/home/CalenderInner.tsx
  src/components/home/Introduce.tsx
  src/components/home/Member.tsx
  src/components/home/Service.tsx
  src/components/home/ToHomePage.tsx
  src/components/home/common.tsx
  src/components/home/icons/LockIcon.tsx
  src/components/home/icons/WaffleIcon.tsx
  src/mocks/handler/homeHandler.ts
  src/mocks/handlers.ts
  src/mocks/types/types.ts
  src/pages/Home.tsx
Labels: enhancement

#13 Feat/markdown
  package.json
  src/components/solve/ProblemDescription/ProblemDescription.tsx
  src/lib/MarkdownRenderer.tsx
  src/pages/Dashboard.tsx
  src/pages/Rookie.tsx
  yarn.lock
Labels: enhancement

#14 hotfix: 누락된 커밋들 추가
  src/components/home/Activity.tsx
  src/components/home/Member.tsx
  src/components/home/icons/WaffleIcon.tsx
Labels: hotfix

#17 Feat/cicd
  .github/workflows/dev.yml
  temp/README.md
  temp/release.yml
Labels: enhancement

#16 Feat/announcement
  public/icon/announcement/ClosedListItem.svg
  public/icon/announcement/OpenedListItem.svg
  src/apis/announcement.ts
  src/main.tsx
  src/mocks/db/announcement.ts
  src/pages/Announcement.tsx
  src/types/apiTypes.ts
Labels: enhancement

#15 Feat/notification modal
  public/icon/Notification.svg
  src/components/Modal/Modal.tsx
  src/components/Modal/useModal.tsx
  src/components/home/Apply.tsx
  src/components/home/NotificationModal.tsx
  src/components/rookie/Header/Header.tsx
  src/components/solve/ProblemDescription/ProblemDescription.tsx
  src/lib/zIndex.ts
  src/pages/Home.tsx
Labels: enhancement
